/*
    Inserts Padrão do Sistema
    Se deseja dar um "reset" no Sistema, execute o conteúdo de db.sql e depois este.
*/
INSERT INTO config (meta, value) VALUES 
    ('title', 'Módulo GTG'), 
    ('style', 'light'), 
    ('logo', ''),
    ('logo_icon', ''),
    ('login_img', 'storage/users/user1/plain-blue-background.jpg'),
    ('email', 'natanael@gtg.software');

INSERT INTO usuario_tipo (id, name_sing, name_plur) VALUES 
    (1, 'Administrador', 'Administradores'), 
    (2, 'Usuário', 'Usuários');
    
INSERT INTO usuario (id, utip_id, name, password, email, slug, token, date_c, date_m) VALUES 
    (1, 1, 'Admin', '$2y$10$jgZeTK87biVK07FOJRZRZu6MJdtK18Bu35gUMsHkpursqjGKBsatO', 'admin@gtg.software', 'adm', '', '2022-04-07', '2022-04-07');

INSERT INTO email_template (id, usu_id, name, subject, content, meta, date_c, date_m) VALUES 
    (1,1,'Redefinir Senha','Redefina Sua Senha!','%3Ctable+align%3D%27center%27+style%3D%27background-color%3A+%23363636%3B+width%3A+100%25%3B+margin%3A+0+auto%3B+border-radius%3A+5px%3B%27%3E%0D%0A++++++++%3Cthead%3E%0D%0A++++++++++++%3Cth+style%3D%27text-align%3A+center%27%3E%0D%0A++++++++++++++++%3Cimg+style%3D%27padding-left%3A+20px%3B+padding-top%3A+10px%3B+padding-bottom%3A+10px%3B+padding-right%3A+20px%3B%27+%0D%0A++++++++++++++++++++src%3D%27%7Blogo%7D%27+height%3D%2760px%27%3E%0D%0A++++++++++++%3C%2Fth%3E%0D%0A++++++++++++%3Cth+style%3D%27text-align%3A+center%3B%27%3E%0D%0A++++++++++++++++%3Ch1+style%3D%27color%3A+rgb%28255%2C+255%2C+255%29%3B+text-align%3A+center%3B%27%3E%7Btitle%7D%3C%2Fh1%3E%0D%0A++++++++++++%3C%2Fth%3E%0D%0A++++++++%3C%2Fthead%3E%0D%0A++++%3C%2Ftable%3E%0D%0A++++%3Cdiv+style%3D%27margin-top%3A+20px%3B+padding-bottom%3A+20px%3B%27%3E%0D%0A++++++++%3Ch2%3ERedefina+sua+senha%3C%2Fh2%3E%0D%0A++++++++%3Cp%3ERecebemos+uma+tentativa+de+recupera%C3%A7%C3%A3o+de+senha+do+site+do+%7Bpath%7D+para+este+e-mail.+%0D%0A++++++++++++Caso+n%C3%A3o+tenha+solicitado%2C+desconsidere+esse+e-mail.+Caso+contr%C3%A1rio%2C+clique+no+link+de+verifica%C3%A7%C3%A3o+abaixo%3A%3C%2Fp%3E%0D%0A++++%3C%2Fdiv%3E%0D%0A++++%3Cdiv%3E%0D%0A++++++++%3Cp+style%3D%27text-align%3A+center%3B%27%3E%0D%0A++++++++++++%3Ca+href%3D%27%7Bpath%7D%2Fredefinir-senha%2F%7Buser_token%7D%27%3E%0D%0A++++++++++++++++Clique+aqui+para+redefinir+sua+senha%0D%0A++++++++++++%3C%2Fa%3E%0D%0A++++++++%3C%2Fp%3E%0D%0A++++%3C%2Fdiv%3E','redefine_password','2022-01-07 17:12:00','2022-01-07 17:12:00'),
    (2,1,'Cadastro do Usuário','Você se Registrou com Sucesso!','%3Ctable+align%3D%27center%27+style%3D%27background-color%3A+%23363636%3B+width%3A+100%25%3B+margin%3A+0+auto%3B+border-radius%3A+5px%3B%27%3E%0D%0A++++++++%3Cthead%3E%0D%0A++++++++++++%3Cth+style%3D%27text-align%3A+center%27%3E%0D%0A++++++++++++++++%3Cimg+style%3D%27padding-left%3A+20px%3B+padding-top%3A+10px%3B+padding-bottom%3A+10px%3B+padding-right%3A+20px%3B%27+%0D%0A++++++++++++++++++++src%3D%27%7Blogo%7D%27+height%3D%2760px%27%3E%0D%0A++++++++++++%3C%2Fth%3E%0D%0A++++++++++++%3Cth+style%3D%27text-align%3A+center%3B%27%3E%0D%0A++++++++++++++++%3Ch1+style%3D%27color%3A+rgb%28255%2C+255%2C+255%29%3B+text-align%3A+center%3B%27%3E%7Btitle%7D%3C%2Fh1%3E%0D%0A++++++++++++%3C%2Fth%3E%0D%0A++++++++%3C%2Fthead%3E%0D%0A++++%3C%2Ftable%3E%0D%0A++++%3Cdiv+style%3D%27margin-top%3A+20px%3B+padding-bottom%3A+20px%3B%27%3E%0D%0A++++++++%3Ch4+style%3D%27text-align%3A+center%27%3EOl%C3%A1%2C+%7Buser_name%7D%21%3C%2Fh4%3E%0D%0A++++++++%3Cp+style%3D%27text-align%3A+center%27%3EAqui+est%C3%A3o+os+seus+dados+de+cadastro+no+%7Btitle%7D%3A%3C%2Fp%3E%0D%0A++++++++%3Cbr%3E%0D%0A++++++++%3Cp%3E%3Cstrong%3ENome%3A+%3C%2Fstrong%3E+%7Buser_name%7D%3C%2Fp%3E%0D%0A++++++++%3Cp%3E%3Cstrong%3EE-mail%3A+%3C%2Fstrong%3E+%7Buser_email%7D%3C%2Fp%3E%0D%0A++++++++%3Cp%3E%3Cstrong%3ESenha%3A+%3C%2Fstrong%3E+%7Buser_pass%7D%3C%2Fp%3E%0D%0A++++%3Cdiv%3E','user_registered','2022-01-07 17:13:00','2022-04-21 20:13:00');

INSERT INTO menu (id, utip_id, name, meta, content) VALUES 
    (1,0,'Header {user_type}','header-architect','{\n    \"items\": [\n        {\n            \"desc\": \"Início\",\n            \"url\": \"entrar\",\n            \"icon\": \"nav-link-icon fa fa-home\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Contato\",\n            \"url\": \"contato\",\n            \"icon\": \"nav-link-icon fa fa-phone\",\n            \"type\": \"item\",\n            \"level\": 1\n        }\n    ]\n}'),
    (2,0,'Left {user_type}','left-architect','{\n    \"items\": []\n}'),
    (3,1,'Header {user_type}','header-architect','{\n    \"items\": [\n        {\n            \"desc\": \"Início\",\n            \"url\": \"entrar\",\n            \"icon\": \"nav-link-icon fa fa-home\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Contato\",\n            \"url\": \"contato\",\n            \"icon\": \"nav-link-icon fa fa-phone\",\n            \"type\": \"item\",\n            \"level\": 1\n        }\n    ]\n}'),
    (4,1,'Left {user_type}','left-architect','{\n    \"items\": [\n        {\n            \"desc\": \"Painéis\",\n            \"url\": \"#\",\n            \"icon\": \"\",\n            \"type\": \"heading\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Painel Principal\",\n            \"url\": \"admin\",\n            \"icon\": \"metismenu-icon pe-7s-display2\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Criar Usuário\",\n            \"url\": \"admin/usuarios/criar\",\n            \"icon\": \"metismenu-icon pe-7s-add-user\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"E-mails\",\n            \"url\": \"#\",\n            \"icon\": \"\",\n            \"type\": \"heading\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Todos os E-mails\",\n            \"url\": \"admin/emails\",\n            \"icon\": \"metismenu-icon pe-7s-mail\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Criar E-mail\",\n            \"url\": \"admin/emails/criar\",\n            \"icon\": \"metismenu-icon pe-7s-mail\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Configurações\",\n            \"url\": \"#\",\n            \"icon\": \"\",\n            \"type\": \"heading\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Aparência\",\n            \"url\": \"#\",\n            \"icon\": \"metismenu-icon pe-7s-look\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Editar Menus\",\n            \"url\": \"admin/menus\",\n            \"icon\": \"metismenu-icon pe-7s-menu\",\n            \"type\": \"item\",\n            \"level\": 2\n        }\n    ]\n}'),
    (5,2,'Header {user_type}','header-architect','{\n    \"items\": [\n        {\n            \"desc\": \"Início\",\n            \"url\": \"entrar\",\n            \"icon\": \"nav-link-icon fa fa-home\",\n            \"type\": \"item\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Contato\",\n            \"url\": \"contato\",\n            \"icon\": \"nav-link-icon fa fa-phone\",\n            \"type\": \"item\",\n            \"level\": 1\n        }\n    ]\n}'),
    (6,2,'Left {user_type}','left-architect','{\n    \"items\": [\n        {\n            \"desc\": \"Painéis\",\n            \"url\": \"#\",\n            \"icon\": \"\",\n            \"type\": \"heading\",\n            \"level\": 1\n        },\n        {\n            \"desc\": \"Painel Principal\",\n            \"url\": \"u\",\n            \"icon\": \"metismenu-icon pe-7s-display2\",\n            \"type\": \"item\",\n            \"level\": 1\n        }\n    ]\n}');
