<script src="<?= url("public/assets/js/jquery-3.0.0.min.js") ?>"></script>
<script src="<?= url("public/assets/js/bootstrap.min.js") ?>"></script>
<script src="<?= url("public/assets/js/bootstrap.bundle.min.js") ?>"></script>
<script src="<?= url("resources/views/themes/architect-ui/assets/scripts/main.js") ?>"></script>
<script src="<?= url("public/assets/js/toastr.min.js") ?>"></script>
<script src="<?= url("public/assets/js/jquery-ui.js") ?>"></script>
<script src="<?= url("public/assets/js/jquery.ui.touch-punch.js") ?>"></script>
<script src="<?= url("public/assets/js/jquery.maskedinput.min.js") ?>"></script>
<script src="<?= url("resources/js/tinymce.min.js") ?>"></script>
<script src="<?= url("resources/js/data-table.js") ?>"></script>
<script src="<?= url("resources/js/app.js") ?>"></script>